version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Assicurati che questa cartella contenga i tuoi file 'app.py', 'templates', e 'static'
    command: python app.py
